### ISSUE TITLE
ext install ChaunceyKiwi.json-tree-view doesn't work? 

### ISSUE THREAD

**Issue by dataassistant** [ChaunceyKiwi/json-tree-view#11]
Hello,
I'm trying to install this extension but it doesn't seem to be found.

Codium/Linux

ext install ChaunceyKiwi.json-tree-view

**Comment by lszyba1** [comment]
you are #1 search on google for json tree , but for some reason your extension does not show up in vscode

**Comment by ChaunceyKiwi** [comment]
Please provide more details to reproduce the issue so I can assist. Can you install it through extension marketplace?
